
import Image from 'next/image/';
import Link from 'next/link';
import Head from 'next/head'

function DiningSet() {
    return (
        <div>
            <div>
            <Head>
        <title>BedsDivan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo (1).png" />
        
      </Head>
      <div>
      <div className="header section">
          {/* <ul>
              <li><Link href="/new">New</Link>
              <li><Link href="/product/Divanbed">Divan</Link></li>
              </li>
              
          </ul> */}
      
      <div className="classic-header">
        <div className="header-top section-fluid   ">
                    <div className="container">
                        <div className="row row-cols-lg-2 align-items-center">
                            
                    <div className="col text-center text-lg-left">
                                <div className="header-top-massege">
                                    <p>Free Delivery over £40 to most of UK*</p>
                                </div>
                            </div>
                           
                    <div className="col d-none d-lg-block">
                                <div className="header-top-set-lan-curr d-flex justify-content-end">
                            <div className="header-top-content">
                                       <a href="/contact"> <button> Contact Us </button></a>
                
                                    </div>
                                   
                                    <div className="header-top-content">
                                    <a href="/about">   <button>About us</button></a>
                                        
                                    </div>
                                    <div className="header-top-content">
                                        <button>01902405535</button>

                                    </div>
                                    
                        </div>
                            </div>
                        
                </div>
                    </div>
                </div>
                </div>
      <div className="header-bottom d-none d-lg-block">
                    <div className="container position-relative Ncs ">
                        <div className="row align-self-center">
                           
                    <div className="col-md-2 align-self-center">
                                <div className="header-logo">
                                    <a href=""><Image alt="BedsDivan" src="/assets/images/logo/logo.png" width={118} height={118}  /></a> 
                                </div>
                            </div>
                            <div className="col-md-6 align-self-center">
                                <div className="header-actions search-section">
                                    <div className="header_search-form">
                                        
                                        <form className="action-form" action="#">
                                            <input className="form-control" placeholder="Search for Products----------------" type="text" />
                                            <button className="submit" type="submit"><i className="icon-magnifier"></i></button>
                                        </form>

                                    </div>
                                    <a href="#" className="header-action-btn header-action-btn-cart" title="Wishlist">
                                    <i className="icon-heart"></i>
                                        <span className="header-action-num">05</span>
                                    </a>
                                    <a href="#" className="header-action-btn header-action-btn-cart offcanvas-toggle pr-0">
                                        <i className="icon-handbag"></i>
                                        <span className="header-action-num">01</span>

                                    </a>

                                    
                                </div>
                            </div>

                            <div className="col-md-4 align-self-center">
                                <div className="header-actions">
                                   
                                        
                            <div className="header-bottom-set dropdown">
                                        <ul>
                                            <button className="login-button"><a href="#" style={{color:"#262884"}}> <b>Login</b> </a></button>
                                            
                                            <button className="ReadMorB"> <span style={{color:"#7c7c7c"}}>or</span>  <a href="#" style={{color:"#292929"}}> <b>Register</b> </a></button>
                                            <button className="box-imgN"><Image alt="BedsDivan" src="/assets/images/banner/Group358.png" width={58} height={50} /></button>
                                        </ul>
                                            
                                            
                                        </div>
                                       
                            
                                        
                                    </div>
                                </div>
                               
                </div>
                        </div>
                    </div>
      <div className="header-bottom d-lg-none sticky-nav bg-white">
                        <div className="container position-relative">
                            <div className="row align-self-center">
                               
                    <div className="col-auto align-self-center">
                                    <div className="header-logo">
                                        <a href="#"><Image src="/assets/images/logo/logo.png" width={128} height={128}  alt="Site Logo" /></a>
                                    </div>
                                </div>
                      
                               
                    <div className="col align-self-center">
                                    <div className="header-actions">
                                        <div className="header_account_list">
                                            <a href="javascript:void(0)" className="header-action-btn search-btn"><i
                                                className="icon-magnifier"></i></a>
                                            <div className="dropdown_search">
                                                <form className="action-form" action="#">
                                                    <input className="form-control" placeholder="Enter your search key" type="text" />
                                                        <button className="submit" type="submit"><i className="icon-magnifier"></i></button>
                                    </form>
                                </div>
                                            </div>
                                           
                            <div className="header-bottom-set dropdown">
                                                <button className="dropdown-toggle header-action-btn" data-bs-toggle="dropdown"><i
                                                    className="icon-user"></i></button>
                                                <ul>
                                                    <li><a className="dropdown-item" href="my-account.html">My account</a></li>
                                                    <li><a className="dropdown-item" href="checkout.html">Checkout</a></li>
                                                    <li><a className="dropdown-item" href="login.html">Sign in</a></li>
                                                </ul>
                                            </div>
                                            
                            <a href="#offcanvas-cart" className="header-action-btn header-action-btn-cart offcanvas-toggle pr-0">
                                                <i className="icon-handbag"></i>
                                                <span className="header-action-num">01</span>
                                               
                            </a>
                                            <a href="#offcanvas-mobile-menu" className="header-action-btn header-action-btn-menu offcanvas-toggle d-lg-none">
                                                <i className="icon-menu"></i>
                                            </a>
                                            
                                        </div>
                                    </div>
                                    
                </div>
                            </div>
                        </div>
                        <div className="d-none d-lg-block sticky-nav" style={{backgroundColor:"#204697"}}>
            <div className="container position-relative" style={{maxWidth:"100%"}}>
                <div className="row">
                    <div className="col-md-12 align-self-center">
                        <div className="main-menu manu-color-white">
                            <ul>
                            {/* <li className="dropdown position-static"><a href="/DivanBed"> <b>Divan Beds</b> </a> */}
                            <li className="dropdown position-static "><Link className="ForBold" href="/product/Divanbed">  Divan Beds</Link>
                                    <ul className="mega-menu d-block">
                                        <li className="d-flex">
                                        <ul className="d-block">
                                            <li>
                                                    <a className="p-0 " href="shop-left-sidebar.html"><Image className="img-responsive w-100 "  src="/assets/images/banner/beds-nav.jpg" width={258} height={238}  alt="BedsDivan" /></a>
                                                </li>
                                            </ul>
                                            
                                             <ul className="d-block">
                                                <li className="title"><a href="#" style={{color:"#262884"}}> <b> Shop by Type </b></a></li>
                                                <li><a href="shop-3-column.html">Linen Fabric Divan Beds</a></li>
                                                <li><a href="shop-4-column.html">Velvet Fabric Divan Beds</a></li>
                                                <li><a href="shop-left-sidebar.html">Suede Fabric Divan Bed</a></li>
                                                <li><a href="shop-right-sidebar.html">Low Divan Beds</a></li>
                                                <li><a href="shop-right-sidebar.html">Leather Divan Beds</a></li>
                                                <li><a href="shop-right-sidebar.html" style={{color:"#262884"}}> <b>View All</b> </a></li>
                                            </ul>
                                            <ul className="d-block">
                                                <li className="title"><a href="#" style={{color:"#262884"}}> <b> Shop by size </b></a></li>
                                                <li><a href="single-product.html">Small Single (2?6)</a></li>
                                                <li><a href="single-product-variable.html">Single (3?0)</a></li>
                                                <li><a href="single-product-affiliate.html">Small Double (4?0)</a></li>
                                                <li><a href="single-product-group.html">Double (4?6)</a></li>
                                                <li><a href="single-product-tabstyle-2.html">King (5?0)</a></li>
                                                <li><a href="single-product-tabstyle-3.html">Super King (6?0)</a></li>
                                            </ul>
                                            <ul className="d-block" style={{marginRight:"0px !important"}}>
                                                <li className="title"><a href="#" style={{color:"#262884"}}> <b> Divan Beds Complete Set</b></a></li>
                                                <li><a href="shop-3-column.html">Linen Fabric Divan Beds</a></li>
                                               
                                            </ul>
                                           
                                            
                                        </li>
                                        <li>
                                        </li>
                                    </ul>
                                </li>
                                <li className="dropdown position-static"><Link className="ForBold" href="/product/AllBeds"  > All Beds    </Link>
                             
                             <ul className="mega-menu d-block">
                                 <li className="d-flex">
                                 <ul className="d-block">
                                     <li>
                                             <a className="p-0" href="shop-left-sidebar.html"><Image className="img-responsive w-100" src="/assets/images/banner/Mattresses-nav.jpg" width={258} height={238}  alt="BedsDivan" /></a>
                                         </li>
                                     </ul>
                                     <ul className="d-block">
                                     <li className="title"><a href="#" style={{color:"#262884"}}> <b> Sleigh Beds </b></a></li>
                                         <li><a href="shop-3-column.html">Florida Bed Range</a></li>
                                         <li><a href="shop-4-column.html">Ambassador Range</a></li>
                                         <li><a href="shop-right-sidebar.html">Kendall Bed</a></li>
                                         <li><a href="shop-right-sidebar.html">Manoco Range</a></li>
                                         <li><a href="shop-right-sidebar.html">Royal Beds</a></li>
                                         <li><a href="shop-right-sidebar.html">Swan Bed Range</a></li>
                                         <li><a href="shop-right-sidebar.html">Wing Bed Range</a></li>
                                         <li><a href="shop-right-sidebar.html">Winchester Bed</a></li>
                                         
                                     </ul> 
                                     <ul className="d-block">
                                         <li className="title1"><a href="#" style={{color:"#262884"}}> <b>Ottoman Beds</b> </a></li>
                                         <li className="title1"><a href="#" style={{color:"#262884"}}> <b>Kids Beds</b> </a></li>
                                         <li className="title1"><a href="#" style={{color:"#262884"}}> <b>Leather beds</b> </a></li>
                                         <li className="title1"><a href="#" style={{color:"#262884"}}> <b>Nevada Beds</b> </a></li>
                                         <li className="title1"><a href="#" style={{color:"#262884"}}> <b>Storage Bed</b> </a></li>
                                     </ul>
                                     <ul className="d-block" style={{marginRight:"0px !important"}}>
                                                <li className="title"><a href="#" style={{color:"#262884"}}> <b> Divan Beds </b></a></li>
                                                <li><a href="shop-3-column.html">Linen Fabric Divan Beds</a></li>
                                                <li><a href="shop-4-column.html">Velvet Fabric Divan Beds</a></li>
                                                <li><a href="shop-left-sidebar.html">Suede Fabric Divan Bed</a></li>
                                                <li><a href="shop-right-sidebar.html">Low Divan Beds</a></li>
                                                <li><a href="shop-right-sidebar.html">Leather Divan Beds</a></li>
                                                <li><a href="shop-right-sidebar.html" style={{color:"#262884"}}> <b>View All</b> </a></li>
                                            </ul>
                                    
                                    
                                 </li>
                                
                             </ul>
                         </li>
                         <li className="dropdown position-static"><Link href="/product/Headboard">  Headboard   </Link>
                              
                              <ul className="mega-menu d-block">
                                  <li className="d-flex">
                                  <ul className="d-block">
                                      <li>
                                              <a className="p-0" href="shop-left-sidebar.html"><Image className="img-responsive w-100" src="/assets/images/banner/headboard-nav.jpg" width={258} height={238}  alt="BedsDivan" /></a>
                                          </li>
                                      </ul>
                                      <ul className="d-block">
                                          <li className="title"> <a href="#" style={{color:"#262884"}}> <b>Shop by Type</b> </a> </li>
                                          <li><a href="#">Panerl Headboard</a></li>
                                          <li><a href="#">Cube Headboard</a></li>
                                          <li><a href="#">Plain Headboard</a></li>
                                          <li><a href="#" style={{color:"#262884"}}> <b>View All</b> </a></li> 

                                      </ul>
                                      
                                      
                                     <ul className="d-block">
                                          <li className="title"><a href="#" style={{color:"#262884"}}> <b>Shop by size</b> </a></li>
                                          <li><a href="single-product.html">Small Single (2?6)</a></li>
                                          <li><a href="single-product-variable.html">Single (3?0)</a></li>
                                          <li><a href="single-product-affiliate.html">Small Double (4?0)</a></li>
                                          <li><a href="single-product-group.html">Double (4?6)</a></li>
                                          <li><a href="single-product-tabstyle-2.html">King (5?0)</a></li>
                                          <li><a href="single-product-tabstyle-3.html">Super King (6?0)</a></li>
                                      </ul> 
                                     
                                  </li>
                                 
                              </ul>
                          </li>
                                <li className="dropdown position-static"><a href="/Mattressess"> <b>Mattresses </b>  </a>
                               
                                    <ul className="mega-menu d-block">
                                        <li className="d-flex">
                                        <ul className="d-block">
                                            <li>
                                                    <a className="p-0" href="shop-left-sidebar.html"><Image className="img-responsive w-100" src="/assets/images/banner/Mattresses-nav.jpg" width={258} height={238}  alt="BedsDivan" /></a>
                                                </li>
                                            </ul>
                                            <ul className="d-block">
                                            <li className="title"><a href="#" style={{color:"#262884"}}> <b> Shop by Type </b></a></li>
                                                <li><a href="shop-3-column.html">Plain Headboard</a></li>
                                                <li><a href="shop-4-column.html">Panel Headboard</a></li>
                                                <li><a href="shop-right-sidebar.html">Cube Headboard</a></li>
                                                <li><a href="shop-left-sidebar.html" style={{color:"#262884"}}> <b>View All</b> </a></li>
                                            </ul> 
                                            <ul className="d-block">
                                                <li className="title"><a href="#" style={{color:"#262884"}}> <b>Shop by size</b> </a></li>
                                                <li><a href="single-product.html">Small Single (2?6)</a></li>
                                                <li><a href="single-product-variable.html">Single (3?0)</a></li>
                                                <li><a href="single-product-affiliate.html">Small Double (4?0)</a></li>
                                                <li><a href="single-product-group.html">Double (4?6)</a></li>
                                                <li><a href="single-product-tabstyle-2.html">King (5?0)</a></li>
                                                <li><a href="single-product-tabstyle-3.html">Super King (6?0)</a></li>
                                            </ul>
                                            <ul className="d-block">
                                                <li className="title"><a href="#" style={{color:"#262884"}}> <b>Shop by Comfort</b> </a></li>
                                                <li><a href="single-product.html">Very Firm</a></li>
                                                <li><a href="single-product-variable.html">Firm</a></li>
                                                <li><a href="single-product-affiliate.html">Medium</a></li>
                                                <li><a href="single-product-group.html">Soft</a></li>
                                            </ul>
                                           
                                           
                                           
                                        </li>
                                       
                                    </ul>
                                </li> 
                                

                                <li className="dropdown position-static"><Link className="ForBold" href="/product/Sofa">Sofa   </Link>
                                {/* <i
                                            className="ion-ios-arrow-down"></i> */}
                                    <ul className="mega-menu d-block">
                                        <li className="d-flex">
                                        <ul className="d-block">
                                            <li>
                                                    <a className="p-0" href="shop-left-sidebar.html"><Image width={258} height={238}  className="img-responsive w-100" src="/assets/images/banner/Mattresses-nav.jpg" alt="BedsDivan" /></a>
                                                </li>
                                            </ul>
                                            <ul className="d-block">
                                            <li className="title"><a href="#" style={{color:"#262884"}}> <b> Shop by Type </b></a></li>
                                                <li><a href="shop-3-column.html">Chair beds</a></li>
                                                <li><a href="shop-4-column.html">2 seater sofa beds</a></li>
                                                <li><a href="shop-right-sidebar.html">3 seater sofa beds</a></li>
                                                <li><a href="shop-right-sidebar.html">4 seater sofa beds</a></li>
                                                <li><a href="shop-right-sidebar.html">Corner sofa beds</a></li>
                                                <li><a href="shop-right-sidebar.html">Storage sofa beds</a></li>
                                                <li><a href="shop-right-sidebar.html">Fabric sofa beds</a></li>
                                                <li><a href="shop-right-sidebar.html">Chairs</a></li>
                                                <li><a href="shop-right-sidebar.html">Footstools</a></li>
                                            </ul> 
                                            <ul className="d-block">
                                                <li className="title"><a href="#" style={{color:"#262884"}}> <b>Fabric Sofa</b> </a></li>
                                                <li><a href="single-product.html">Champion Sofa</a></li>
                                                <li><a href="single-product-variable.html">Chicago Sofa</a></li>
                                            </ul>
                                            <ul className="d-block">
                                                <li className="title1"><a href="#" style={{color:"#262884"}}> <b>Leather beds</b> </a></li>
                                                <li className="title1"><a href="#" style={{color:"#262884"}}> <b>Nevada Beds</b> </a></li>
                                                <li className="title1"><a href="#" style={{color:"#262884"}}> <b>Storage Bed</b> </a></li>
                                            </ul>
                                           
                                           
                                        </li>
                                       
                                    </ul>
                                </li> 
                                <li className="dropdown position-static"><Link href="/product/GardenFurniture">Garden Furniture   </Link>
                                {/* <i
                                            className="ion-ios-arrow-down"></i> */}
                                            
                                    <ul className="mega-menu d-block">
                                        <li className="d-flex">
                                        <ul className="d-block">
                                            <li>
                                                    <a className="p-0" href="shop-left-sidebar.html"><Image width={258} height={238} className="img-responsive w-100" src="/assets/images/banner/Mattresses-nav.jpg" alt="BedsDivan" /></a>
                                                </li>
                                            </ul>
                                            <ul className="d-block">
                                            <li className="title"><a href="#" style={{color:"#262884"}}> <b> Shop by Type </b></a></li>
                                                <li><a href="shop-3-column.html">Chair beds</a></li>
                                                <li><a href="shop-4-column.html">2 seater sofa beds</a></li>
                                                <li><a href="shop-right-sidebar.html">3 seater sofa beds</a></li>
                                                <li><a href="shop-right-sidebar.html">4 seater sofa beds</a></li>
                                                <li><a href="shop-right-sidebar.html">Corner sofa beds</a></li>
                                                <li><a href="shop-right-sidebar.html">Storage sofa beds</a></li>
                                                <li><a href="shop-right-sidebar.html">Fabric sofa beds</a></li>
                                                <li><a href="shop-right-sidebar.html">Chairs</a></li>
                                                <li><a href="shop-right-sidebar.html">Footstools</a></li>
                                            </ul> 
                                            <ul className="d-block">
                                                <li className="title"><a href="#" style={{color:"#262884"}}> <b>Fabric Sofa</b> </a></li>
                                                <li><a href="single-product.html">Champion Sofa</a></li>
                                                <li><a href="single-product-variable.html">Chicago Sofa</a></li>
                                            </ul>
                                            <ul className="d-block">
                                                <li className="title1"><a href="#" style={{color:"#262884"}}> <b>Leather beds</b> </a></li>
                                                <li className="title1"><a href="#" style={{color:"#262884"}}> <b>Nevada Beds</b> </a></li>
                                                <li className="title1"><a href="#" style={{color:"#262884"}}> <b>Storage Bed</b> </a></li>
                                            </ul>
                                           
                                           
                                        </li>
                                       
                                    </ul>
                                </li> 
                               
                               
                                {/* <li className="dropdown "><a href="#"> <b> Garden Furniture </b></a>
                                    <ul className="sub-menu">
                                        <li className="dropdown position-static"><a href="blog-grid-left-sidebar.html">Garden Sofa Sets
                                             </a> 
                                        </li>
                                        <li className="dropdown position-static"><a href="blog-list-left-sidebar.html">Garden Dining Sets
                                            </a>
                                        </li>
                                    </ul>
                                </li> */}

                                <li className="dropdown position-static"><Link href="/product/LivingRoom"> Living Room Furniture  </Link>
                                {/* <i
                                            className="ion-ios-arrow-down"></i> */}
                                    <ul className="mega-menu d-block">
                                        <li className="d-flex">
                                        <ul className="d-block">
                                            <li>
                                                    <a className="p-0" href="shop-left-sidebar.html"><Image width={258} height={238}  className="img-responsive w-100" src="/assets/images/banner/Mattresses-nav.jpg" alt="BedsDivan" /></a>
                                                </li>
                                            </ul>
                                            <ul className="d-block">
                                                <li className="title1"><a href="#" style={{color:"#262884"}}> <b>Chest Drawers</b> </a></li>
                                                <li className="title1"><a href="#" style={{color:"#262884"}}> <b>Shelf</b> </a></li>
                                                <li className="title1"><a href="#" style={{color:"#262884"}}> <b>Wardrobes</b> </a></li>
                                                <li className="title1"><a href="#" style={{color:"#262884"}}> <b>Nevada Beds</b> </a></li>
                                                <li className="title1"><a href="#" style={{color:"#262884"}}> <b>Storage Bed</b> </a></li>
                                            </ul>
                                            
                                            <ul className="d-block">
                                                <li className="title"><a href="#" style={{color:"#262884"}}> <b>Chairs</b> </a></li>
                                                <li><a href="single-product.html">Arm Chairs</a></li>
                                                <li><a href="single-product-variable.html">Rocking Chairs</a></li>
                                                <li><a href="single-product-variable.html">Lounge Chairs</a></li>
                                            </ul> 
                                        </li>
                                       
                                    </ul>
                                </li> 



                                <li className="dropdown position-static"><Link href="/product/DiningSet"> Dining Set   </Link>
                                {/* <i
                                            className="ion-ios-arrow-down"></i> */}
                                    <ul className="mega-menu d-block">
                                        <li className="d-flex">
                                        <ul className="d-block">
                                            <li>
                                                    <a className="p-0" href="shop-left-sidebar.html"><Image width={258} height={238}  className="img-responsive w-100" src="/assets/images/banner/Mattresses-nav.jpg" alt="BedsDivan" /></a>
                                                </li>
                                            </ul>
                                            <ul className="d-block">
                                            <li className="title"><a href="#" style={{color:"#262884"}}> <b> Dining Table Set </b></a></li>
                                                <li><a href="shop-3-column.html">2 Seater Dining Sets</a></li>
                                                <li><a href="shop-4-column.html">4 Seater Dining Sets</a></li>
                                                <li><a href="shop-right-sidebar.html">6 Seater Dining Sets</a></li>
                                                <li><a href="shop-right-sidebar.html">4 seater sofa beds</a></li>
                                                <li><a href="shop-right-sidebar.html">8 Seater Dining Sets</a></li>
                                                <li><a href="shop-right-sidebar.html" style={{color:"#262884"}}><b>View All</b></a></li>
                                            </ul> 
                                            
                                            <ul className="d-block">
                                                <li className="title1"><a href="#" style={{color:"#262884"}}> <b>Dining Chairs</b> </a></li>
                                                <li className="title1"><a href="#" style={{color:"#262884"}}> <b>Dining Tables</b> </a></li>
                                                <li className="title1"><a href="#" style={{color:"#262884"}}> <b>Sideboards</b> </a></li>
                                            </ul>
                                           
                                           
                                        </li>
                                       
                                    </ul>
                                </li> 
                                 <li><a href="contact.html" style={{color:"red"}}> <b>Sale</b> </a></li>
                               
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>  
        </div>

        <div className="section hero-slide-item2">
        <div className="container ">
            <div className="row">
                <div className="col-md-6">
                    <div className="mt-10 For-margin">
                    <h2 className="DivanPageL"><b>Sales on Modern Stylish  <br />Dining Table</b></h2> <br />
                    <p className="mt-4" style={{color:"#141414",fontSize:"15px"}}>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, <br /> sed diam nonumy eirmod tempor invidunt ut labore et dolore <br /> magna aliquyam erat, sed diam voluptua. At vero eos et <br /> accusam et justo duo dolores et ea rebum. Stet clita kasd <br /> gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
                         </p>
                         <div className="mt-10">
                            <button className="ShopMobile " style={{color:"#ffffff", backgroundColor:"#EC9E17", padding:"9px", borderRadius: "42px",paddingLeft:"26px",paddingRight:"26px", fontSize:"16px", paddingTop:"7px",paddingBottom: "5px" }}> <b>SHOP NOW</b> </button>
                        </div>
                      
                    </div>
                </div>
                <div className="col-md-6 mt-8 MobileSection" style={{position:"relative", left:"16px"}}>
                    <Image width={600} height={400} className="responsiveImage"  src="/assets/images/LivingRoom/Group 556.png"  alt="product" />
                </div>
            </div>

        </div>


    </div>

    <div className="section mt-2" style={{backgroundColor:"#EC9E17"}}>
        <div className="container text-center p-3" >
            <h3 style={{color:"#141414"}}> <strong> Quick Delivery - </strong>Shop our beds available within 2 weeks</h3>

        </div>


    </div>
    <div className="BodyMobileHeight" style={{backgroundColor:"#f3f3f8",height:"1156px"}}> 
    <div className="section mb-10 pt-100px  ">
        <div className="container-fluid">
            
            <div className="row">
                        <div className="col-md-12 text-center" data-aos="fade-up">
                            <div className="section-title">
                                <h2 className="title" style={{color:"#222178", fontWeight:"700"}}>  Shop by Seating</h2>
                               </div>
                        </div>



            </div>
                    <div className="row">
                    <div className="size-box">
<div className="single-box">
                               <a href="#"> <Image width={180} height={100} src="/assets/images/DivanBedsicon/Group 477.svg" alt="Product" /></a>
                                 
                                <p className="text-center  mt-2" style={{color:"#222178" }}> <b> 2 Seater </b></p>
                                 
</div>

                            <div className="single-box">
                               <a href="#"> <Image width={180} height={100} src="/assets/images/DivanBedsicon/Group 478.svg" alt="Product" /></a>
                                <p className="text-center  mt-2" style={{color:"#222178" }}> <b> 4 Seater</b></p>
                            </div>


                            <div className="single-box">
                                <a href="#"><Image width={180} height={100} src="/assets/images/DivanBedsicon/Group 479.svg"  alt="Product"/></a>
                                <p className="text-center  mt-2" style={{color:"#222178" }}> <b> 6 Seater </b></p>
                            </div>

                            <div className="single-box">
                                <a href="#"><Image width={180} height={100} src="/assets/images/DivanBedsicon/Group 480.svg" alt="Product" /></a>
                                <p className="text-center mt-2" style={{color:"#222178" }}>
                                    <b> 8 Seater</b>
                                </p>
                            </div>

                            {/* <div className="single-box">
                                <a href="#"><Image width={180} height={100} src="/assets/images/DivanBedsicon/Group 481.svg" alt="Product"/></a>
                                <p className="text-center mt-2" style={{color:"#222178" }}>
                                  <b> Super King</b>
                                </p>
                            </div> */}
                    </div>
                        
                        



                    </div>
                    
            
        </div>
    </div>
    
    <div className="container">
                    <div className="row">
                        <div className="col-md-12 text-center" data-aos="fade-up">
                            <div className="section-title mb-0">
                                <h2 className="title colorfirst">BedsDivans.co.uk</h2>  </div>
                            <p className="sub-title mb-6" style={{fontWeight:"600"}}> We’re one of the UK’s leading manufacturers of <span style={{color:"#262884"}}>cheap divan beds</span> , offering a rich selection of products in a variety of styles. At BedsDivans, we are committed to improving comfort and sleep quality without compromising style. We believe shopping for a bed, mattress, or set of <span style={{color:"#262884"}}>rattan furniture</span>  for your garden should be an enjoyable experience all the way through. </p>
                        <hr />
                        </div>
                        </div>
                   
           
           </div>
           <div className="section">
               <div className="container">
                   <div className="row mt-6">
                       <div className="col-md-6 bg-white" style={{position:"relative", left:"105px"}}>
                           <div className="Sofa-Heading">
                               <h3 style={{color:"#1E196C" }}> <b> Exclusive Offers on Sofa & Sofa Beds </b></h3>
                               <p className="mt-2" style={{color:"#7C7C7C",fontSize:"13px"}}>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed <br /> diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam</p>

                           </div>
                           <div  style={{marginTop:"43px",marginLeft:"37px",marginBottom:"60px"}}>
                            <button className="ShopMobile" style={{color:"#ffffff", backgroundColor:"#f22222", padding:"9px", borderRadius: "0px",paddingLeft:"33px",paddingRight:"37px", fontSize:"18px", paddingTop:"7px",paddingBottom: "5px" }}> <b>SHOP NOW</b> </button>
                        </div>

                       </div>
                       <div className="col-md-6  "  style={{ backgroundColor:"transparent", position:"relative", left:"197px",width: "0%"}} >
                           <Image width={500} height={500} src="/assets/images/DivanBedsicon/Group 501.png" className="" alt="" />

                       </div>

                   </div>
               </div>

           </div>
           <div className="section mb-10  pt-100px bg-white MobileShopClr">
        <div className="container-fluid">
            
            <div className="row">
                        <div className="col-md-12 text-center" data-aos="fade-up">
                            <div className="section-title">
                                <h2 className="title" style={{color:"#222178", fontWeight:"700"}}>  Shop By Color</h2>
                               </div>
                        </div>



            </div>
                    <div className="row">
                    <div className="size-box">
<div className="single-box">
                               <a href="#"> <Image width={180} height={100} src="/assets/images/DivanBedsicon/Mask Group 20.png" alt="Product" /></a>
                                 
                                <p className="text-center  mt-2" style={{color:"#222178" }}> <b> Cotton </b></p>
                                 
</div>

                            <div className="single-box">
                               <a href="#"> <Image width={180} height={100} src="/assets/images/DivanBedsicon/Mask Group 21.png" alt="Product" /></a>
                                <p className="text-center  mt-2" style={{color:"#222178" }}> <b> Cotton </b></p>
                            </div>


                            <div className="single-box">
                                <a href="#"><Image width={180} height={100} src="/assets/images/DivanBedsicon/Mask Group 22.png" alt="Product" /></a>
                                <p className="text-center  mt-2" style={{color:"#222178" }}> <b> Cotton </b></p>
                            </div>

                            <div className="single-box">
                                <a href="#"><Image width={180} height={100} src="/assets/images/DivanBedsicon/Mask Group 23.png" alt="Product" /></a>
                                <p className="text-center mt-2" style={{color:"#222178" }}>
                                    <b> Cotton</b>
                                </p>
                            </div>

                            <div className="single-box">
                                <a href="#"><Image width={180} height={100} src="/assets/images/DivanBedsicon/Mask Group 24.png" alt="Product" /></a>
                                <p className="text-center mt-2" style={{color:"#222178" }}>
                                  <b> Leather</b>
                                </p>
                            </div>
                    </div>
                        
                        



                    </div>
                    
            
        </div>
    </div>
    <div className="section hero-slide-itemLivibg">
        <div className="container ">
            <div className="row">
                <div className="col-md-12">
                    <div className="mt-8 For-margin">
                    <h2 className="DivanPageH2Li" style={{marginTop:"10px"}}><b>Latest and elegant Dining Tables</b></h2>
                    <p className="mt-4" style={{color:"#141414",fontSize:"15px"}}>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, <br /> sed diam nonumy eirmod tempor invidunt ut labore <br /> et dolore magna</p>
                         <div  style={{marginTop:"75px",marginBottom:"83px"}}>
                            <button className="ShopMobile" style={{color:"#ffffff", backgroundColor:"#f22222", padding:"9px", borderRadius: "0px",paddingLeft:"33px",paddingRight:"37px", fontSize:"18px", paddingTop:"7px",paddingBottom: "5px" }}> <b>SHOP NOW</b> </button>
                        </div>
                       
                    </div>
                </div>
            </div>

        </div>


    </div>
    {/* <div className="section hero-slide-item8">
        <div className="container ">
            <div className="row">
                <div className="col-md-12">
                    <div className="mt-10 For-margin">
                    <h2 className="SofaPageH2" style={{marginTop:"10px"}}><b>Exclusive offer on <br /> Slender 3 Seater Sofa</b></h2>
                    <p className="mt-4" style={{color:"#000",fontSize:"15px"}}>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, <br /> sed  diam nonumy eirmod tempor invidunt ut labore et <br /> dolore magna</p>
                         <div className="mt-10">
                            <button className="ShopMobile" style={{color:"#ffffff", backgroundColor:"#f22222", padding:"9px", borderRadius: "0px",paddingLeft:"33px",paddingRight:"37px", fontSize:"18px", paddingTop:"7px",paddingBottom: "5px" }}> <b>SHOP NOW</b> </button>
                        </div>
                       
                    </div>
                </div>
                
            </div>

        </div>


    </div> */}
    <div className="container mt-10">
    <div className="text-center">
        <h4 style={{color:"#F22222"}}> <b> OUR EXCLUSIVE </b> </h4>
        <h2 className="title mt-2" style={{color:"#222178", fontWeight:"800"}}>  Complete Divan Bed Set Range</h2>
        <p className="mt-2 mb-6" style={{color:"#7c7c7c",fontSize:"15px"}}>Lorem ipsum dolor sit amet, consetetur sadipscing elitr,  sed diam nonumy eirmod <br /> tempor invidunt ut labore  et dolore magna</p>

    </div>

    <div className="row">
                                            <div className="col-lg-3 col-md-6 col-sm-6 col-xs-6 mb-6" data-aos="fade-up" data-aos-delay="200">

                                                <div className="product productfor2">
                                                    <div className="thumb thumbfor2">
                                                        <a href="shop-left-sidebar.html" className="image imagefor2">
                                                            <Image src="/assets/images/product-image/1.jpg" alt="Product" width={210} height={10} />
                                                            {/* <Image className="hover-image" src="/assets/images/product-image/2.jpg" width={180} height={180} alt="Product" /> */}
                                                        </a>
                                                        <span className="badges">
                                                            <span className="new" style={{fontSize:"18px"}}>50% OFF</span>
                                                        </span>

                                                        <p className="sale">
                                                            APRIL SALE
                                            </p>


                                                    </div>
                                                    <div className="content reco-pr">

                                                        <h5 className="title"><a href="shop-left-sidebar.html">Simple minimal Chair </a></h5>
                                                        <span className="price">

                                                            <span className="old">NOW $48.50</span>
                                                            <span className="new">FROM $38.50</span>
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="col-lg-3 col-md-6 col-sm-6 col-xs-6 mb-6" data-aos="fade-up" data-aos-delay="400">

                                                <div className="product productfor2">
                                                    <div className="thumb thumbfor2">
                                                        <a href="shop-left-sidebar.html" className="image imagefor2">
                                                        <Image src="/assets/images/product-image/1.jpg" alt="Product" width={210} height={10} />
                                                            {/* <Image width={180} height={100} className="hover-image" src="assets/images/product-image/2.jpg" alt="Product" /> */}
                                                        </a>
                                                        <span className="badges">
                                                            <span className="new" style={{fontSize:"18px"}}>50% OFF</span>
                                                        </span>

                                                        <p className="sale">
                                                            APRIL SALE
                                            </p>


                                                    </div>
                                                    <div className="content reco-pr">

                                                        <h5 className="title"><a href="shop-left-sidebar.html">Simple minimal Chair </a></h5>
                                                        <span className="price">

                                                            <span className="old">NOW $48.50</span>
                                                            <span className="new">FROM $38.50</span>
                                                        </span>
                                                    </div>
                                                </div>

                                            </div>
                                            <div className="col-lg-3 col-md-6 col-sm-6 col-xs-6 mb-6" data-aos="fade-up" data-aos-delay="600">

                                                <div className="product productfor2">
                                                    <div className="thumb thumbfor2">
                                                        <a href="shop-left-sidebar.html" className="image imagefor2">
                                                        <Image src="/assets/images/product-image/1.jpg" alt="Product" width={210} height={10} />
                                                            {/* <Image width={180} height={100} className="hover-image" src="assets/images/product-image/2.jpg" alt="Product" /> */}
                                                        </a>
                                                        <span className="badges">
                                                            <span className="new" style={{fontSize:"18px"}}>50% OFF</span>
                                                        </span>

                                                        <p className="sale">
                                                            APRIL SALE
                                            </p>


                                                    </div>
                                                    <div className="content reco-pr">

                                                        <h5 className="title"><a href="shop-left-sidebar.html">Simple minimal Chair </a></h5>
                                                        <span className="price">

                                                            <span className="old">NOW $48.50</span>
                                                            <span className="new">FROM $38.50</span>
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="col-lg-3 col-md-6 col-sm-6 col-xs-6 mb-6" data-aos="fade-up" data-aos-delay="800">

                                                <div className="product productfor2">
                                                    <div className="thumb thumbfor2">
                                                        <a href="shop-left-sidebar.html" className="image imagefor2">
                                                        <Image src="/assets/images/product-image/1.jpg" alt="Product" width={210} height={10} />
                                                            {/* <Image width={180} height={100} className="hover-image" src="assets/images/product-image/2.jpg" alt="Product" /> */}
                                                        </a>
                                                        <span className="badges">
                                                            <span className="new" style={{fontSize:"18px"}}>50% OFF</span>
                                                        </span>

                                                        <p className="sale">
                                                            APRIL SALE
                                            </p>


                                                    </div>
                                                    <div className="content reco-pr">

                                                        <h5 className="title"><a href="shop-left-sidebar.html">Simple minimal Chair </a></h5>
                                                        <span className="price">

                                                            <span className="old">NOW $48.50</span>
                                                            <span className="new">FROM $38.50</span>
                                                        </span>
                                                    </div>
                                                </div>

                                            </div>
                                            <div className="col-lg-3 col-md-6 col-sm-6 col-xs-6 mb-md-30px mb-lm-30px" data-aos="fade-up" data-aos-delay="200">

                                                <div className="product productfor2">
                                                    <div className="thumb thumbfor2">
                                                        <a href="shop-left-sidebar.html" className="image imagefor2">
                                                        <Image src="/assets/images/product-image/1.jpg" alt="Product" width={210} height={10} />
                                                            {/* <Image width={180} height={100} className="hover-image" src="assets/images/product-image/2.jpg" alt="Product" /> */}
                                                        </a>
                                                        <span className="badges">
                                                            <span className="new" style={{fontSize:"18px"}}>50% OFF</span>
                                                        </span>

                                                        <p className="sale">
                                                            APRIL SALE
                                            </p>


                                                    </div>
                                                    <div className="content reco-pr">

                                                        <h5 className="title"><a href="shop-left-sidebar.html">Simple minimal Chair </a></h5>
                                                        <span className="price">

                                                            <span className="old">NOW $48.50</span>
                                                            <span className="new" >FROM $38.50</span>
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="col-lg-3 col-md-6 col-sm-6 col-xs-6  mb-md-30px mb-lm-30px" data-aos="fade-up" data-aos-delay="400">

                                                <div className="product productfor2">
                                                    <div className="thumb thumbfor2">
                                                        <a href="shop-left-sidebar.html" className="image imagefor2">
                                                        <Image src="/assets/images/product-image/1.jpg" alt="Product" width={210} height={10} />
                                                            {/* <Image width={180} height={100} className="hover-image" src="assets/images/product-image/2.jpg" alt="Product" /> */}
                                                        </a>
                                                        <span className="badges">
                                                            <span className="new" style={{fontSize:"18px"}}>50% OFF</span>
                                                        </span>

                                                        <p className="sale">
                                                            APRIL SALE
                                            </p>


                                                    </div>
                                                    <div className="content reco-pr">

                                                        <h5 className="title"><a href="shop-left-sidebar.html">Simple minimal Chair </a></h5>
                                                        <span className="price">

                                                            <span className="old">NOW $48.50</span>
                                                            <span className="new">FROM $38.50</span>
                                                        </span>
                                                    </div>
                                                </div>

                                            </div>
                                            <div className="col-lg-3 col-md-6 col-sm-6 col-xs-6 mb-es-30px" data-aos="fade-up" data-aos-delay="600">

                                                <div className="product productfor2">
                                                    <div className="thumb thumbfor2">
                                                        <a href="shop-left-sidebar.html" className="image imagefor2">
                                                        <Image src="/assets/images/product-image/1.jpg" alt="Product" width={210} height={10} />
                                                            {/* <Image width={180} height={100} className="hover-image" src="assets/images/product-image/2.jpg" alt="Product" /> */}
                                                        </a>
                                                        <span className="badges">
                                                            <span className="new" style={{fontSize:"18px"}}>50% OFF</span>
                                                        </span>

                                                        <p className="sale">
                                                            APRIL SALE
                                            </p>


                                                    </div>
                                                    <div className="content reco-pr">

                                                        <h5 className="title"><a href="shop-left-sidebar.html">Simple minimal Chair </a></h5>
                                                        <span className="price">

                                                            <span className="old">NOW $48.50</span>
                                                            <span className="new">FROM $38.50</span>
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="col-lg-3 col-md-6 col-sm-6 col-xs-6 " data-aos="fade-up" data-aos-delay="800">

                                                <div className="product productfor2">
                                                    <div className="thumb thumbfor2">
                                                        <a href="shop-left-sidebar.html" className="image imagefor2">
                                                        <Image src="/assets/images/product-image/1.jpg" alt="Product" width={210} height={10} />
                                                            {/* <Image width={180} height={100} className="hover-image" src="assets/images/product-image/2.jpg" alt="Product" /> */}
                                                        </a>
                                                        <span className="badges">
                                                            <span className="new" style={{fontSize:"18px"}}>50% OFF</span>
                                                        </span>

                                                        <p className="sale">
                                                            APRIL SALE
                                            </p>


                                                    </div>
                                                    <div className="content reco-pr">

                                                        <h5 className="title"><a href="shop-left-sidebar.html">Simple minimal Chair </a></h5>
                                                        <span className="price">

                                                            <span className="old">NOW $48.50</span>
                                                            <span className="new">FROM $38.50</span>
                                                        </span>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        </div>

                                        <div className="section pb-100px pt-100px bg-brown">
                <div className="container-fluid coustmer-review">
                    <div className="row">
                        <div className="col-md-12" data-aos="fade-up">
                            <div className="section-title text-center mb-11">
                                <h2 className="title colorsecond">DISCOVER THE BENEFITS OF SHOPPING ONLINE AT BEDSDIVANS</h2>
                                <p>When looking for a new bed why not try the new designed divan bed. It is affordable and looks great. At bedsdivans we spent years in improving our wide selection of beds and we can assure you will love our latest selection of divan beds.
At Bedsdivans we aim to work around your needs whether it comes to short notice delivery dates or the slightest adjustment to your bed we are always here to help you get the bed right for you.</p>
                            </div>
                        </div>
                    </div>

                    <div className="text-center">
  
                <div className="">
                 <a href="#" className="btn btn-primary" style={{borderRadius:"36px", marginBottom:"23px"}}>More Services</a>
                    </div>
</div>



 
                   
                    <div className="row border">
                        <div className="col-md-3 CoustmerReviewMobile">
                            <div className="review-card">
                                <article className="review">
                                    <aside className="review__consumer-information">
                                        <div className="consumer-information">
                                            <div className="consumer-information__picture">
                                                {/* <Image width={128} height={128} alt="BedsDivan" src="https://www.bedsdivans.co.uk/wp-content/uploads/2019/08/dummy-pic.png" className="lazyloaded" data-ll-status="loaded" /> */}
</div>
                                                <div className="consumer-information__details">
                                                    <div className="consumer-information__name">
                                                        Jodie Nash </div>
                                                    <div className="consumer-information__data">
                                                        <div className="consumer-information__review-count">
                                                            <i className="fa fa-pencil-square-o" aria-hidden="true"></i>
                                                            <span>1 reviews</span>
                                                        </div>
                                                        <div className="consumer-information__location">
                                                            <i className="fa fa-map-marker" aria-hidden="true"></i>
                                                            <span>GB</span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
</aside>
                                        <section className="review__content">
                                            <div className="review-content__header" v-pre="">
                                                <div className="review-content-header">
                                                    <div className="star-rating--medium">
                                                        {/* <Image width={128} height={128} src="https://cdn.trustpilot.net/brand-assets/4.1.0/stars/stars-5.svg" alt="5 stars: Excellent" className="lazyloaded" data-ll-status="loaded" /> */}
</div>
                                                        <div className="review-content-header__dates">
                                                            <span className="trigger" >4 hours ago</span>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div className="review-content__body">
                                                    <h2 className="review-content__title">
                                                        Excellent service excelle
</h2>
                                                    <p className="review-content__text">
                                                        Excellent service excellent bed... </p>
                                                </div>
</section>
                                            <div className="review__actions">
                                                <div className="review-actions">
                                                    <div className="review-actions__main">
                                                        <div className="review-action brand-find-useful">
                                                            <button className="button--subtle button--subtle-label-below">
                                                                <i className="fa fa-thumbs-o-up" aria-hidden="true"></i>
                                                                <span>Useful</span>
                                                            </button></div>

                                                        <div className="brand-share-button-wrapper">
                                                            <button className="button--subtle button--subtle-label-below">
                                                                <i className="fa fa-share-alt" aria-hidden="true"></i>
                                                                <span>Share</span>
                                                            </button>
                                                        </div>
                                                        <div className="review-action reply">
                                                            <button className="button--subtle button--subtle-label-below">
                                                                <i className="fa fa-reply" aria-hidden="true"></i>
                                                                <span>Reply</span>
                                                            </button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
</article>
</div>
</div>
                                <div className="col-md-3 CoustmerReviewMobile">
                                    <div className="review-card">
                                        <article className="review">
                                            <aside className="review__consumer-information">
                                                <div className="consumer-information">
                                                    <div className="consumer-information__picture">
                                                        {/* <Image width={128} height={128} alt="BedsDivan" src="https://www.bedsdivans.co.uk/wp-content/uploads/2019/08/dummy-pic.png" className="lazyloaded" data-ll-status="loaded" /><noscript><Image alt="BedsDivan" src="https://www.bedsdivans.co.uk/wp-content/uploads/2019/08/dummy-pic.png" /></noscript> */}
</div>
                                                        <div className="consumer-information__details">
                                                            <div className="consumer-information__name">
                                                                Mary Fletcher </div>
                                                            <div className="consumer-information__data">
                                                                <div className="consumer-information__review-count">
                                                                    <i className="fa fa-pencil-square-o" aria-hidden="true"></i>
                                                                    <span>8 reviews</span>
                                                                </div>
                                                                <div className="consumer-information__location">
                                                                    <i className="fa fa-map-marker" aria-hidden="true"></i>
                                                                    <span>GB</span>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
</aside>
                                                <section className="review__content">
                                                    <div className="review-content__header" v-pre="">
                                                        <div className="review-content-header">
                                                            <div className="star-rating--medium">
                                                                {/* <Image width={128} height={128}  src="https://cdn.trustpilot.net/brand-assets/4.1.0/stars/stars-5.svg" alt="5 stars: Excellent" className="lazyloaded" data-ll-status="loaded" /> */}
                                                            </div>
                                                            <div className="review-content-header__dates">
                                                                <span className="trigger" >7 hours ago</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div className="review-content__body">
                                                        <h2 className="review-content__title">
                                                            Over the mood with
</h2>
                                                        <p className="review-content__text">
                                                            My order arrived when they said it would... </p>
                                                    </div>
                                                </section>
                                                <div className="review__actions">
                                                    <div className="review-actions">
                                                        <div className="review-actions__main">
                                                            <div className="review-action brand-find-useful">
                                                                <button className="button--subtle button--subtle-label-below">
                                                                    <i className="fa fa-thumbs-o-up" aria-hidden="true"></i>
                                                                    <span>Useful</span>
                                                                </button></div>

                                                            <div className="brand-share-button-wrapper">
                                                                <button className="button--subtle button--subtle-label-below">
                                                                    <i className="fa fa-share-alt" aria-hidden="true"></i>
                                                                    <span>Share</span>
                                                                </button>
                                                            </div>
                                                            <div className="review-action reply">
                                                                <button className="button--subtle button--subtle-label-below">
                                                                    <i className="fa fa-reply" aria-hidden="true"></i>
                                                                    <span>Reply</span>
                                                                </button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
</article>
</div>
                                    </div>
                                    <div className="col-md-3 CoustmerReviewMobile">
                                        <div className="review-card">
                                            <article className="review">
                                                <aside className="review__consumer-information">
                                                    <div className="consumer-information">
                                                        <div className="consumer-information__picture">
                                                            {/* <Image width={128} height={128} alt="BedsDivan" src="https://www.bedsdivans.co.uk/wp-content/uploads/2019/08/dummy-pic.png" className="lazyloaded" data-ll-status="loaded" /> */}
                                                        </div>
                                                        <div className="consumer-information__details">
                                                            <div className="consumer-information__name">
                                                                Emma Bridgman </div>
                                                            <div className="consumer-information__data">
                                                                <div className="consumer-information__review-count">
                                                                    <i className="fa fa-pencil-square-o" aria-hidden="true"></i>
                                                                    <span>4 reviews</span>
                                                                </div>
                                                                <div className="consumer-information__location">
                                                                    <i className="fa fa-map-marker" aria-hidden="true"></i>
                                                                    <span>GB</span>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </aside>
                                                <section className="review__content">
                                                    <div className="review-content__header" v-pre="">
                                                        <div className="review-content-header">
                                                            <div className="star-rating--medium">
                                                                {/* <Image width={128} height={128}  src="https://cdn.trustpilot.net/brand-assets/4.1.0/stars/stars-5.svg" alt="5 stars: Excellent" className="lazyloaded" data-ll-status="loaded" /> */}
                                                            </div>
                                                            <div className="review-content-header__dates">
                                                                <span className="trigger" >9 hours ago</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div clasclassNames="review-content__body">
                                                        <h2 className="review-content__title">
                                                            Small double divan bed
</h2>
                                                        <p className="review-content__text">
                                                            Bed and headboard both lovely... </p>
                                                    </div>
                                                </section>
                                                <div className="review__actions">
                                                    <div className="review-actions">
                                                        <div className="review-actions__main">
                                                            <div className="review-action brand-find-useful">
                                                                <button className="button--subtle button--subtle-label-below">
                                                                    <i className="fa fa-thumbs-o-up" aria-hidden="true"></i>
                                                                    <span>Useful</span>
                                                                </button></div>

                                                            <div className="brand-share-button-wrapper">
                                                                <button className="button--subtle button--subtle-label-below">
                                                                    <i className="fa fa-share-alt" aria-hidden="true"></i>
                                                                    <span>Share</span>
                                                                </button>
                                                            </div>
                                                            <div className="review-action reply">
                                                                <button className="button--subtle button--subtle-label-below">
                                                                    <i className="fa fa-reply" aria-hidden="true"></i>
                                                                    <span>Reply</span>
                                                                </button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </article>
                                        </div>
                                    </div>
                                    <div className="col-md-3 CoustmerReviewMobile">
                                        <div className="review-card">
                                            <article className="review">
                                                <aside className="review__consumer-information">
                                                    <div className="consumer-information">
                                                        <div className="consumer-information__picture">
                                                            {/* <Image width={128} height={128} alt="BedsDivan" src="https://www.bedsdivans.co.uk/wp-content/uploads/2019/08/dummy-pic.png" className="lazyloaded" data-ll-status="loaded" /> */}
                                                        </div>
                                                        <div className="consumer-information__details">
                                                            <div className="consumer-information__name">
                                                                David whitham </div>
                                                            <div className="consumer-information__data">
                                                                <div className="consumer-information__review-count">
                                                                    <i className="fa fa-pencil-square-o" aria-hidden="true"></i>
                                                                    <span>4 reviews</span>
                                                                </div>
                                                                <div className="consumer-information__location">
                                                                    <i className="fa fa-map-marker" aria-hidden="true"></i>
                                                                    <span>GB</span>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </aside>
                                                <section className="review__content">
                                                    <div className="review-content__header" v-pre="">
                                                        <div className="review-content-header">
                                                            <div className="star-rating--medium">
                                                                {/* <Image width={128} height={128}  src="https://cdn.trustpilot.net/brand-assets/4.1.0/stars/stars-5.svg" alt="5 stars: Excellent" className="lazyloaded" data-ll-status="loaded" /> */}
                                                            </div>
                                                            <div className="review-content-header__dates">
                                                                <span className="trigger" >7 hours ago</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div className="review-content__body">
                                                        <h2 className="review-content__title">
                                                            Excellent service and fas
</h2>
                                                        <p className="review-content__text">
                                                            Excellent service and fast delivery... </p>
                                                    </div>
                                                </section>
                                                <div className="review__actions">
                                                    <div className="review-actions">
                                                        <div className="review-actions__main">
                                                            <div className="review-action brand-find-useful">
                                                                <button className="button--subtle button--subtle-label-below">
                                                                    <i className="fa fa-thumbs-o-up" aria-hidden="true"></i>
                                                                    <span>Useful</span>
                                                                </button></div>

                                                            <div className="brand-share-button-wrapper">
                                                                <button className="button--subtle button--subtle-label-below">
                                                                    <i className="fa fa-share-alt" aria-hidden="true"></i>
                                                                    <span>Share</span>
                                                                </button>
                                                            </div>
                                                            <div className="review-action reply">
                                                                <button className="button--subtle button--subtle-label-below">
                                                                    <i className="fa fa-reply" aria-hidden="true"></i>
                                                                    <span>Reply</span>
                                                                </button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </article>
                                        </div>
                                    </div>
                                </div>



                   
                    </div>
            </div>

<div className="footer-area">
        <div className="footer-container">
            <div className="footer-top">
                <div className="container">
                    <div className="row">
                        
                        <div className="col-md-6 col-lg-4 mb-md-30px mb-lm-30px" data-aos="fade-up" data-aos-delay="200">
                            <div className="single-wedge ">
                                <Image width={128} height={128} className="" src="/assets/images/logo/logo.png"   alt="" />
                                <p className=" my-2 sahil"><i className="fa fa-arrow-circle-right " aria-hidden="true"></i>Unit 8A Stag Industrial Estate,</p>
                                <p>Oxford Street, Bilston,</p>
                                <p>WV14 &nbsp;7HZ,</p>
                                <p>01902 &nbsp;405535,</p>
                                <p><i className="fa fa-envelope-o" aria-hidden="true"></i>&nbsp;&nbsp;info@bedsdivans.co.uk</p>
                                <p className="my-5"><Image width={128} height={128} src="/assets/images/logo/yell.jpg"   alt="" />&nbsp;Trusted by Yell</p>
                                {/* <p className="footer-herading my-2"><i className="fa fa-arrow-circle-right" aria-hidden="true"></i>Unit 8A Stag Industrial Estate</p> */}
                                
                                
                            </div>
                        </div>
                        
                        <div className="col-md-6 col-sm-6 col-lg-3 mb-md-30px mb-lm-30px footer2-margin" data-aos="fade-up" data-aos-delay="400">
                            <div className="single-wedge">
                                <h4 className="footer-herading">USEFUL LINKS</h4>
                                <div className="footer-links">
                                    <div className="footer-row">
                                        <ul className="align-items-center">
                                            <li className="li"><a className="single-link" href="about.html">Diven Beds</a></li>
                                            <li className="li"><a className="single-link" href="#">Suede Divan Bed</a></li>
                                            <li className="li"><a className="single-link" href="privacy-policy.html">Headboards</a></li>
                                            <li className="li"><a className="single-link" href="#">Mattressess</a></li>
                                            <li className="li"><a className="single-link" href="#">Velvet Fabric Diven Beds</a></li>
                                            <li className="li"><a className="single-link" href="#">Sleigh Beds</a></li>
                                        </ul>
                                        <hr className="my-4" />
                                        <ul className="align-items-center">
                                        <h4 className="footer-herading my-6">BLOGS</h4>
                                            <li className="li"><a className="single-link" href="about.html">A Buying Guide To Distinct Sized Mattress</a></li>
                                            
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div className="col-md-6 col-lg-2 col-sm-6 mb-lm-30px" data-aos="fade-up" data-aos-delay="600">
                            <div className="single-wedge">
                                <h4 className="footer-herading">Additional links</h4>
                                <div className="footer-links">
                                    <div className="footer-row">
                                        <ul className="align-items-center">
                                            <li className="li"><a href="/about" className="single-link" >About Us</a>
                                            </li>
                                            <li className="li"><a className="single-link" href="/Shop">Shop</a></li>
                                            <li className="li"><a href="/contact" className="single-link"  >Contact Us</a></li>
                                            <li className="li"><a className="single-link" href="/ReturnPolicy">Return Policy</a></li>
                                            <li className="li"><a className="single-link" href="/PrivacyPolicy">Privacy Policy</a></li>
                                            <li className="li"><a className="single-link" href="checkout.html">Diven Bed Yorkshire</a></li>
                                            <li className="li"><a className="single-link" href="checkout.html">Diven Bed Birmingham</a></li>
                                            <li className="li"><a className="single-link" href="checkout.html">Diven Bed London</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                      
                        <div className="col-md-6 col-lg-3 footer-margin" data-aos="fade-up" data-aos-delay="800">
                            <div className="single-wedge">
                                <h4 className="footer-herading">top selected</h4>
                                <div className="footer-links">
                                   
                                    <div id="mc_embed_signup" className="footer-4">
                                    <p>Mink Chenillie Divan Base or <br></br>Set+Headboard+1500 Pocket Mattress<br></br>FREE HOME DILIVERY</p>
                                    <p>White Velvet Cube Headboard</p>
                                    <p>White Crushed Velvet Divan Bed Set <br></br>+Headboard+Mattress FREE UK DILIVERY</p>
                                    <p>Gun Grey Crushed Velvet Divan Set <br></br>+Headboard+1500 Pocket Pillow Top <br></br>Mattress FREE UK DILIVERY</p>
                                    <p>Orthopedic Foam and Spring Mattress <br></br>Medium Frimness</p>
                                    <hr className="my-4" />
                                    <ul className="text-center">
                                       <a href=""> <li><p><i className="fa fa-facebook" aria-hidden="true"></i><span><i className="fa fa-facebook" aria-hidden="true"></i></span><span><i className="fa fa-facebook" aria-hidden="true"></i></span></p></li></a>
                                    </ul>
                                        
                                        {/* <form id="mc-embedded-subscribe-form" className="validate" novalidate="" target="_blank" name="mc-embedded-subscribe-form" method="post" action="http://devitems.us11.list-manage.com/subscribe/post?u=6bbb9b6f5827bd842d9640c82&amp;id=05d85f18ef">
                                            <div id="mc_embed_signup_scroll" className="mc-form">
                                                <input className="email" type="email" required="" placeholder="Your Mail*" name="EMAIL" value="" />
                                                <div className="mc-news" aria-hidden="true">
                                                    <input type="text" value="" tabindex="-1" name="b_6bbb9b6f5827bd842d9640c82_05d85f18ef" />
                                                </div>
                                                <div className="clear">
                                                    <button id="mc-embedded-subscribe" className="button btn-primary" type="submit" name="subscribe" value=""><i
                                                            className="icon-cursor"></i> Send Mail</button>
                                                </div>
                                            </div>
                                        </form>  */}
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
            <hr />
            <div className="container">
                <div className="row">
                <div className="col-md-6 text-left">
                            <p className="copy-text"><strong>Bedsdiven</strong> © 2021</p>
                        </div>

                </div>
                


            </div>




           
        </div>
    </div>

           
    </div> 
      </div>
            </div>
        </div>
    )
}

export default DiningSet
